{% set name = "psfex" %}
{% set version = "3.24.2" %}

package:
  name: astromatic-{{ name }}
  version: {{ version }}

source:
  url: https://github.com/astromatic/{{ name }}/archive/{{ version }}.tar.gz
  sha256: e2c94bf60d90e0db52ad4b8baa5d5fceb483eff6a87b35c6fc5a881fccc04af9
  patches:
    - 0001-Search-lapacke-library.patch

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - autoconf
    - automake
    - libtool
    - make
  host:
    - fftw
    - liblapacke
  run:
    - fftw

test:
  commands:
    - psfex -d

about:
  home: http://www.astromatic.net/software/psfex
  license: GPL-3.0
  license_file: LICENSE
  summary: a utility that makes PSF models for use with the SExtractor program.
  description: |
    PSFEx (PSF Extractor) is a computer program that extracts precise models
    of the Point Spread Functions (PSFs) from images processed by SExtractor
    and measures the quality of images. The generated PSF models can be used
    for model-fitting photometry or morphological analyses.
  doc_url: https://psfex.readthedocs.io/
  dev_url: https://github.com/astromatic/psfex

extra:
  recipe-maintainers:
    - drbixx
    - teake
